[package]
name = "greedia3"
version = "0.1.0"
authors = ["k3d3"]
edition = "2018"

[features]
sctest = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leaky-bucket = "0.7.3"
anyhow = "1.0.32"
tokio = { version = "0.2.22", features = [
    "rt-core",
    "rt-threaded",
    "macros",
    "blocking",
    "fs"
] }
futures = "0.3.5"
serde = { version = "1.0.115", features = ["derive"] }
structopt = "0.3.17"
toml = "0.5.6"
chrono = { version = "0.4.15", features = ["serde"] }
rocksdb = "0.13.0"
oauth2 = { version = "3.0.0", features = ["futures-03", "reqwest-010"] }
reqwest = { version = "0.10.8", features = ["json", "trust-dns"] }
itertools = "0.9.0"
libc = "0.2.76"
rclone-crypt = "0.1.3"
walkdir = "2.3.1"
polyfuse = "0.3.3"
polyfuse-tokio = "0.2.1"
flatbuffers = "0.6.1"
byteorder = "1.3.4"
hex = "0.4.2"
rustc-hash = "1.1.0"
async-trait = "0.1.40"
access-queue = "1.1.0"
serde_json = "1.0.57"
byte-ranger = { path = "byte-ranger" }
async-stream = "0.3.0"
flume = "0.8.4"
bytes = "0.5.6"
